######################################################################
# Automatically generated by qmake (2.01a) pá zá? 26 09:50:27 2008
######################################################################

TEMPLATE = app
TARGET =
CONFIG += qtestlib 
DEPENDPATH += . ../..
INCLUDEPATH += . ../..
QT += xml network
QT -= gui
CONFIG += qt silent #debug


# Input
HEADERS += TMediafly.h ../../Mediafly.h ../../REST.h
SOURCES += TMediafly.cpp ../../Mediafly.cpp ../../REST.cpp

